<?php

/**
* Implements hook_menu().
*/

function citynotifier_menu() {
  $items['richieste/%'] = array(
    'page callback' => 'citynotifier_request',
    'access arguments' => array('View published content'),
    'access callback' => true,
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    );
    
  return $items;
}


/**
* Implementation of hook_services_resources().
*/
function citynotifier_services_resources() {
  return array(
    'login' => array(
      'help' => 'Retrieves graphdata',
      'callback' => 'citynotifier_login',
      'access arguments' => array('view'),
      'access arguments append' => FALSE,
      'args' => array(
        array('name' => 'parameters',
          'type' => 'string',
          'description' => 'The parameters that define requested data',
          'source' => array('path' => '0'), // first argument in the url 
          'optional' => FALSE,
          ),
        ),
      ),
    );
}

/**
* Implements hook_ctools_plugin_api().
*/
function citynotifier_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
      'path' => drupal_get_path('module', 'citynotifier')
    );
  }
}

function citynotifier_login() {
  citynotifier_debug('ciao');
}

function citynotifier_request() {
  _citynotifier_validate_request(func_get_args());
  
}

function _citynotifier_validate_request($args) {
  $index = array("scope","type","subtype","lat","lng","radius","timemin","timemax","status");
  $types = array("all", "problemi_stradali", "emergenze_sanitarie", "reati", "problemi_ambientali", "eventi_pubblici");
  $subtypes = array("all" => array("all"),
                    "problemi_stradali" => array("incidente", "buca", "coda", "lavori_in_corso", "strada_impraticabile"),
                    "emergenze_sanitarie" => array("incidente", "malore", "ferito"),
                    "reati" => array("furto", "attentato"),
                    "problemi_ambientali" => array("incendio", "tornado", "neve", "alluvione"),
                    "eventi_pubblici" => array("partita", "manifestazione", "concerto")); 
  
  $args2validate = array();
  foreach($index as $i => $a)
    $args2validate[$a] = $args[$i];
  
  if($args2validate['scope'] <> "local" && $args2validate['scope'] <> "remote") {
    drupal_add_http_header("Status", 406, "Not validate scope");
    return;
  }
  
  if(!in_array($args2validate['type'], $types)) {
    drupal_add_http_header("Status", 406, "Not validate type");
    return;
  }
  
  if(!in_array($args2validate['subtype'], $subtypes[$args2validate['type']])) {
    drupal_add_http_header("Status", 406, "Not validate subtype");
    return;
  }

  if(!in_array($args2validate['subtype'], $subtypes[$args2validate['type']])) {
    drupal_add_http_header("Status", 406, "Not validate subtype");
    return;
  }
  
  if(!is_float($args2validate['lat'])) {
    drupal_add_http_header("Status", 406, "Not validate lat");
    return;
  }
  

  
  if(!is_float($args2validate['lng'])) {
    drupal_add_http_header("Status", 406, "Not validate lng");
    return;
  }
  
  if(!is_float($args2validate['radius'])) {
    drupal_add_http_header("Status", 406, "Not validate radius");
    return;
  }
  
  //var_dump($args2validate);
}

function citynotifier_debug($data) {
    if (is_array($data) || is_object($data))
      $data = print_r($data, TRUE);
    $data .= "\n";
    error_log($data, 3, "/tmp/citynotifier_debug.log");
}
