<?php

module_load_include('inc', 'citynotifier');

/**
* Implements hook_menu().
*/

function citynotifier_menu() {
  $items['admin/citynotifier'] = array(
    'title'=>t('Amministrazione di Citynotifier'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_citynotifier_admin_form'),
    'access arguments' => array('citynotifier administrator'),
    'file' => 'citynotifier.admin.inc',
    'type' => MENU_CALLBACK
  );
    
  $items['richieste'] = array(
    'title'=>t('Richiesta'),
    'page callback' => 'citynotifier_request',
    'access arguments' => array('access content'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
    );
  
  $items['segnalazione'] = array(
    'title'=>t('Segnalazione'),
    'page callback' => 'citynotifier_report',
    'access arguments' => array('access content'),
    'access callback' => true,
    'file' => 'citynotifier.admin.inc',
    'type' => MENU_CALLBACK,
    );
  
  $items['notifica'] = array(
    'title'=>t('Notifica'),
    'page callback' => 'citynotifier_notify',
    'access arguments' => array('access content'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
    );
  
  $items['login'] = array(
    'title'=>t('Login'),
    'page callback' => 'citynotifier_login',
    'access arguments' => array('access content'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
    );
 
  $items['logout'] = array(
    'title'=>t('Logout'),
    'page callback' => 'citynotifier_logout',
    'access arguments' => array('access content'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
    );
    
  return $items;
}

/**
* Implements hook_permission().
*/
function citynotifier_permission(){
    return array(
        'citynotifier administrator' => array(
            'title' => t('Amministratore di Citynotifier'),
            'description' => t('Utenti che possono amministrare Citynotifier'),
        ),
    );
}


/**
 * Implements hook_help().
 */
function citynotifier_help($path, $arg) {
  switch ($path) {
    case 'admin/citynotifier':
      $output = '';
      $output .= '<h3>' . t('Amministrazione di citynotifier') . '</h3>';
      $output .= '<p>' . t('Seleziona la url da dove scaricare i server da interrogare e quindi seleziona i server scelti') . '</p>';
      return $output;
  }
}


function citynotifier_login() {
  header('Content-type: application/json');
  $login = drupal_json_decode(file_get_contents("php://input"));
  
  if(!$login['username'] || !$login['password']) {
    watchdog('citynotifier', t('Errore nello username o nella password'), array(), WATCHDOG_WARNING);
    drupal_add_http_header("Status", 406);
    drupal_json_output(array("result" => t("Errore nello username o nella password")));
    return;
  };
   
  if(!user_authenticate($login['username'], $login['password'])) {
    watchdog('citynotifier', t("Username o password sbagliati"), array(), WATCHDOG_WARNING);
    drupal_add_http_header("Status", 406);
    drupal_json_output(array("result" => t("Username o password sbagliati")));
    return;
  }
  
  drupal_add_http_header("Status", 200);
  drupal_json_output(array("result" => t("login effettuato con successo")));
}

function citynotifier_logout() {
  header('Content-type: application/json');
  $result = array("result" => "logout effettuato con successo");
  echo drupal_json_output($result);
}

function citynotifier_request() {
  header('Content-type: application/json');
  
  $validation =_citynotifier_validate($_GET, 'request');
  
  if($validation['code'] <> 200) {
    drupal_add_http_header("Status", $validation['code'], $validation['response']);
    return;
  }
  
  $fake_resp = array("request_time" => 1368095111,
		"result" => "Messaggio di servizio",
		"from_server" => "http://ltw1234.web.cs.unibo.it",
		"events" => array("event_id" => "902438",
			          "type" => array("type" => "problemi_stradali", "subtype" => "incidente"),
			          "description" => array("ommioddio","come na catapulta","","",""),
			          "start_time" => 1368045665,
			          "freshness" => 1368085800,
		                  "status" => "open",
			          "reliability" => 0.8,
			          "number_of_notifications" => 2,
			          "locations" => array(array("lat" => 37.42291810, "lng" => -122.08542120),
						       array("lat" => 37.42291811, "lng" => -122.08542120)
						      )
               			  ),
			    array("event_id" => "902438",
			          "type" => array("type" => "problemi_stradali", "subtype" => "incidente"),
			          "description" => array("mi hanno tamponato","dottore chiami un dottore","che guaio","descr4","descr5"),
			          "start_time" => 1368105698,
			          "freshness" => 1368106058,
		                  "status" => "open",
			          "reliability" => 0.9,
			          "number_of_notifications" => 4,
			          "locations" => array(array("lat" => 37.42291815, "lng" => -122.08542120),
						       array("lat" => 37.42291814, "lng" => -122.08542121),
						       array("lat" => 37.42291812, "lng" => -122.08542122),
						       array("lat" => 37.42291813, "lng" => -122.08542123)
						      )
               			  )
               );
  citynotifier_debug($fake_resp);
  drupal_add_http_header("Status", 200);
  echo drupal_json_output($fake_resp);

}


function citynotifier_debug($data) {
  if (is_array($data) || is_object($data))
    $data = print_r($data, TRUE);
  $data .= "\n";
  error_log($data, 3, "/tmp/citynotifier_debug.log");
}
